from django.http import JsonResponse
from django.shortcuts import render

from .mongo import count_records, latest_records
from .startup import get_scraper_status, start_scraper_once


BAD_DISPLAY_PARTS = (
    "request id:",
    "translationdisclaimer",
    "translations of the content",
    "you need to enable javascript",
    "loading...",
    "content sources",
    "view more",
    "toggle faq",
    "screen reader",
    "cpgrams",
    "calendar",
    "current year text",
    "could not find what you were looking for",
    "india portal 2.0 brochure",
    "no data found",
    "okay cancel",
    "skip to main content",
    "pin code",
    "state/district",
    "select category",
    "categoryselect",
    "locationstate",
    "districtpin code",
    "stateandaman",
    "select state",
    "cloudfront",
    "the request could not be satisfied",
    "we can't connect to the server",
    "there might be too much traffic",
    "generated by cloudfront",
    "showrecentpopularfilters",
    "homeall categories",
)

BAD_SCHOLARSHIP_DISPLAY_PARTS = (
    "top banks for education loan",
    "whatsapp channel",
    "by degree",
    "by subject",
    "by university",
    "by country of interest",
)

FILTER_WORDS = (
    "agriculture",
    "climate change",
    "environmental management",
    "farming",
    "fishing",
    "births, deaths",
    "marriages and child care",
    "citizenship",
    "passports",
    "education and learning",
    "apprenticeships",
    "international grants",
)

API_FIELDS = {
    "umang": ("id", "title", "description", "category", "department", "url"),
    "gov": ("id", "title", "service_type", "department", "description", "url"),
    "myscheme": (
        "id",
        "title",
        "description",
        "eligibility",
        "benefits",
        "category",
        "ministry",
        "department",
        "level",
        "tags",
        "application_process",
        "documents",
        "references",
        "raw_data",
        "url",
    ),
    "india": ("id", "title", "description", "ministry", "category", "url"),
    "scholarships": ("id", "title", "provider", "deadline", "amount", "image_url", "url"),
    "grants": ("id", "title", "organization", "description", "funding_amount", "url"),
    "tenders": (
        "id",
        "source",
        "external_id",
        "title",
        "organization",
        "location",
        "state",
        "country",
        "status",
        "procurement_type",
        "category",
        "tender_value",
        "published_on",
        "deadline",
        "description",
        "source_url",
        "url",
    ),
}

ALL_SCHEME_KINDS = ("umang", "gov", "myscheme", "india")
SCHEME_AND_OPPORTUNITY_KINDS = ALL_SCHEME_KINDS + ("scholarships", "grants", "tenders")

CARD_APIS = {
    "banking-financial-services-and-insurance": {
        "api_key": "banking_financial_services_and_insurance",
        "title": "Banking, Financial Services and Insurance",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("bank", "banking", "finance", "financial", "insurance", "loan", "credit", "pension"),
    },
    "health-wellness": {
        "api_key": "health_wellness",
        "title": "Health & Wellness",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("health", "healthcare", "wellness", "medical", "medicine", "hospital", "ayush"),
    },
    "housing-shelter": {
        "api_key": "housing_shelter",
        "title": "Housing & Shelter",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("housing", "shelter", "house", "home", "awas", "habitat"),
    },
    "public-safety-law-justice": {
        "api_key": "public_safety_law_justice",
        "title": "Public Safety, Law & Justice",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("public safety", "law", "justice", "legal", "police", "court", "crime"),
    },
    "science-it-communications": {
        "api_key": "science_it_communications",
        "title": "Science, IT & Communications",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("science", "technology", "innovation", "digital", "communication", "communications", "it "),
    },
    "skills-employment": {
        "api_key": "skills_employment",
        "title": "Skills & Employment",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("skill", "employment", "training", "job", "livelihood", "apprentice"),
    },
    "social-welfare-empowerment": {
        "api_key": "social_welfare_empowerment",
        "title": "Social Welfare & Empowerment",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("social welfare", "welfare", "empowerment", "social security", "disability", "senior citizen"),
    },
    "sports-culture": {
        "api_key": "sports_culture",
        "title": "Sports & Culture",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("sports", "sport", "culture", "cultural", "talent", "heritage", "art"),
    },
    "transport-infrastructure": {
        "api_key": "transport_infrastructure",
        "title": "Transport & Infrastructure",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("transport", "transportation", "infrastructure", "road", "rail", "vehicle"),
    },
    "travel-tourism": {
        "api_key": "travel_tourism",
        "title": "Travel & Tourism",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("travel", "tourism", "tourist", "hospitality"),
    },
    "utility-sanitation": {
        "api_key": "utility_sanitation",
        "title": "Utility & Sanitation",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("utility", "sanitation", "water", "drinking water", "sewerage", "electricity"),
    },
    "women-and-child": {
        "api_key": "women_and_child",
        "title": "Women and Child",
        "kinds": ALL_SCHEME_KINDS,
        "keywords": ("women", "woman", "child", "children", "girl", "mother", "family welfare"),
    },
    "agriculture": {
        "api_key": "agriculture",
        "title": "Agriculture",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "keywords": ("agriculture", "farmer", "farming", "crop", "kisan", "rural", "fishery", "fisheries"),
    },
    "women-programs": {
        "api_key": "women_programs",
        "title": "Women Programs",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "keywords": ("women", "woman", "girl", "female", "mother", "child", "family welfare"),
    },
    "research-grants": {
        "api_key": "research_grants",
        "title": "Research Grants",
        "kinds": ("grants", "scholarships", "myscheme", "india"),
        "keywords": ("research", "grant", "fellowship", "phd", "doctoral", "scientific", "academic", "professor"),
    },
    "tenders-rfps": {
        "api_key": "tenders_rfps",
        "title": "Tenders/RFPs",
        "kinds": ("tenders",),
        "keywords": ("tender", "rfp", "procurement", "bid", "contract"),
    },
    "startup-msme": {
        "api_key": "startup_msme",
        "title": "Startup/MSME",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "keywords": ("startup", "start-up", "msme", "business", "entrepreneur", "entrepreneurship", "venture"),
    },
    "scholarships": {
        "api_key": "scholarships",
        "title": "Scholarships",
        "kinds": ("scholarships",),
        "keywords": ("scholarship", "fellowship", "tuition", "student", "education"),
    },
}


def _clean_text(value):
    return " ".join((value or "").split())


def _short_text(value, limit=180):
    value = _clean_text(value)
    if len(value) <= limit:
        return value
    return value[:limit].rstrip() + "..."


def _item_kind(item):
    kind = getattr(item, "kind", "")
    if kind:
        return kind

    return {
        "UmangScheme": "umang",
        "GovService": "gov",
        "MyScheme": "myscheme",
        "IndiaScheme": "india",
        "Scholarship": "scholarships",
        "Grant": "grants",
        "TenderListing": "tenders",
    }.get(item.__class__.__name__, "")


def _display_image_url(item):
    image_url = _clean_text(getattr(item, "image_url", "") or "")
    if not image_url:
        return ""

    if _item_kind(item) == "scholarships":
        provider = _clean_text(getattr(item, "provider", "") or "")
        url = _clean_text(getattr(item, "url", "") or "").lower()

        # Buddy4Study "page" entries often expose banner-like assets instead of usable logos.
        if provider == "Buddy4Study" and "/page/" in url:
            return ""

    return image_url


def _source_url(item):
    url = _clean_text(getattr(item, "url", "") or "")
    lowered = url.lower()

    # UMANG records currently only store category SPA URLs, not per-record source pages.
    # Those web.umang.gov.in URLs commonly open as CloudFront 403 pages when clicked directly.
    if _item_kind(item) == "umang" or "web.umang.gov.in" in lowered:
        return ""

    return url


def _search_blob(item):
    values = [
        getattr(item, "title", ""),
        getattr(item, "description", ""),
        getattr(item, "category", ""),
        getattr(item, "department", ""),
        getattr(item, "ministry", ""),
        getattr(item, "service_type", ""),
        getattr(item, "tags", ""),
        getattr(item, "eligibility", ""),
        getattr(item, "benefits", ""),
        getattr(item, "organization", ""),
        getattr(item, "provider", ""),
        getattr(item, "procurement_type", ""),
    ]
    return f" {' '.join(_clean_text(value).lower() for value in values)} "


def _matches_keywords(item, keywords):
    blob = _search_blob(item)
    return any(keyword.lower() in blob for keyword in keywords)


def _is_displayable(item):
    title = _clean_text(getattr(item, "title", ""))
    lowered = title.lower()
    description = _clean_text(getattr(item, "description", "") or "")
    kind = _item_kind(item)
    is_scholarship = kind == "scholarships"

    if not title or len(title) < 8:
        return False
    if len(title) > 180:
        return False
    if lowered.startswith(("http://", "https://", "www.")):
        return False
    if any(part in lowered for part in BAD_DISPLAY_PARTS):
        return False
    if is_scholarship and any(part == lowered or part in lowered for part in BAD_SCHOLARSHIP_DISPLAY_PARTS):
        return False
    if sum(1 for word in FILTER_WORDS if word in lowered) >= 3:
        return False
    if lowered.endswith(("==", "=")) and len(title) > 25:
        return False
    if title.endswith("More") and not description:
        return False
    if kind == "gov":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "service_type", "") or ""),
                _clean_text(getattr(item, "department", "") or ""),
            ]
        )
        if not has_detail:
            return False
    if kind == "myscheme":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "eligibility", "") or ""),
                _clean_text(getattr(item, "benefits", "") or ""),
            ]
        )
        if not has_detail:
            return False
    if is_scholarship:
        url = _clean_text(getattr(item, "url", "") or "").lower()
        provider = _clean_text(getattr(item, "provider", "") or "")
        has_specific_provider = provider not in {"", "WeMakeScholars", "Buddy4Study"}
        has_detail = any(
            [
                has_specific_provider,
                _clean_text(getattr(item, "deadline", "") or ""),
                _clean_text(getattr(item, "amount", "") or ""),
                _clean_text(getattr(item, "image_url", "") or ""),
            ]
        )
        if (
            url in {
                "https://www.wemakescholars.com/scholarship",
                "https://www.buddy4study.com/scholarships",
            }
            and not has_detail
        ):
            return False
    if kind == "tenders":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "organization", "") or ""),
                _clean_text(getattr(item, "deadline", "") or ""),
                _clean_text(getattr(item, "tender_value", "") or ""),
            ]
        )
        if not has_detail:
            return False
    return True


def _card_from_item(item, meta_fields=(), description_field="description"):
    meta = []
    for label, field in meta_fields:
        value = _clean_text(getattr(item, field, "") or "")
        if value:
            meta.append({"label": label, "value": value})

    return {
        "title": _clean_text(item.title),
        "description": _short_text(getattr(item, description_field, "") or ""),
        "url": _source_url(item),
        "image_url": _display_image_url(item),
        "meta": meta,
    }


def _section(title, kind, meta_fields=(), description_field="description", display_limit=24):
    total_count = count_records(kind)
    preview_items = latest_records(kind, limit=display_limit)
    clean_items = [
        _card_from_item(item, meta_fields=meta_fields, description_field=description_field)
        for item in preview_items
        if _is_displayable(item)
    ]
    checked_count = len(preview_items)

    return {
        "title": title,
        "slug": title.lower().replace(" ", "-"),
        "total_count": total_count,
        "checked_count": checked_count,
        "clean_count": len(clean_items),
        "hidden_count": checked_count - len(clean_items),
        "items": clean_items,
    }


def _absolute_request_url(request, url):
    url = _clean_text(url)
    if not url:
        return ""
    return request.build_absolute_uri(url)


def _serialize_item(item, fields):
    return {
        field: getattr(item, field)
        for field in fields
    }


def _filtered_items(kind, predicate=None):
    items = []
    for item in latest_records(kind):
        if not _is_displayable(item):
            continue
        if predicate is not None and not predicate(item):
            continue
        items.append(item)
    return items


def _api_response(request, source, kind, fields, api_key=None, predicate=None):
    items = [
        _serialize_item(item, fields)
        for item in _filtered_items(kind, predicate=predicate)
    ]
    return JsonResponse({
        "source": source,
        "api_key": api_key or kind,
        "count": len(items),
        "results": items,
    })


def _card_api_url(request, slug):
    return _absolute_request_url(request, f"/api/cards/{slug}/")


def _card_api_payload(slug):
    config = CARD_APIS.get(slug)
    if not config:
        config = next(
            (
                card_config
                for card_config in CARD_APIS.values()
                if card_config["api_key"] == slug
            ),
            None,
        )
    if not config:
        return None

    results = []
    for kind in config["kinds"]:
        for item in _filtered_items(kind, predicate=lambda record, config=config: _matches_keywords(record, config["keywords"])):
            row = _serialize_item(item, API_FIELDS[kind])
            row["source_key"] = kind
            results.append(row)

    return {
        "source": config["title"],
        "api_key": config["api_key"],
        "count": len(results),
        "results": results,
    }


def api_index(request):
    endpoints = {
        "umang_schemes": _absolute_request_url(request, "/api/umang-schemes/"),
        "government_services": _absolute_request_url(request, "/api/government-services/"),
        "myscheme": _absolute_request_url(request, "/api/myscheme/"),
        "india_portal_schemes": _absolute_request_url(request, "/api/india-portal-schemes/"),
        "scholarships": _absolute_request_url(request, "/api/scholarships/"),
        "grants": _absolute_request_url(request, "/api/grants/"),
        "tenders": _absolute_request_url(request, "/api/tenders/"),
        "scraper_status": _absolute_request_url(request, "/api/scraper-status/"),
    }
    card_endpoints = {
        config["api_key"]: _card_api_url(request, slug)
        for slug, config in CARD_APIS.items()
    }
    return JsonResponse({"endpoints": endpoints, "card_endpoints": card_endpoints})


def api_umang_schemes(request):
    return _api_response(
        request,
        "UMANG Schemes",
        "umang",
        API_FIELDS["umang"],
        api_key="umang_schemes",
    )


def api_government_services(request):
    return _api_response(
        request,
        "Government Services",
        "gov",
        API_FIELDS["gov"],
        api_key="government_services",
    )


def api_myscheme(request):
    return _api_response(
        request,
        "myScheme",
        "myscheme",
        API_FIELDS["myscheme"],
        api_key="myscheme",
    )


def api_india_portal_schemes(request):
    return _api_response(
        request,
        "India Portal Schemes",
        "india",
        API_FIELDS["india"],
        api_key="india_portal_schemes",
    )


def api_scholarships(request):
    return _api_response(
        request,
        "Scholarships",
        "scholarships",
        API_FIELDS["scholarships"],
        api_key="scholarships",
    )


def api_grants(request):
    return _api_response(
        request,
        "Grants",
        "grants",
        API_FIELDS["grants"],
        api_key="grants",
    )


def api_tenders(request):
    return _api_response(
        request,
        "Tenders/RFPs",
        "tenders",
        API_FIELDS["tenders"],
        api_key="tenders",
    )


def api_card(request, slug):
    payload = _card_api_payload(slug)
    if payload is None:
        return JsonResponse({"error": "Unknown card API."}, status=404)
    return JsonResponse(payload)


def api_scraper_status(request):
    return JsonResponse(get_scraper_status())


def home(request):
    sections = [
        _section(
            "UMANG Schemes",
            "umang",
            meta_fields=(("Category", "category"), ("Department", "department")),
        ),
        _section(
            "Government Services",
            "gov",
            meta_fields=(("Type", "service_type"), ("Department", "department")),
        ),
        _section(
            "myScheme",
            "myscheme",
            meta_fields=(("Category", "category"), ("Level", "level"), ("Ministry", "ministry")),
        ),
        _section(
            "India Portal Schemes",
            "india",
            meta_fields=(("Category", "category"), ("Ministry", "ministry")),
        ),
        _section(
            "Scholarships",
            "scholarships",
            meta_fields=(("Provider", "provider"), ("Deadline", "deadline"), ("Award", "amount")),
        ),
        _section(
            "Grants",
            "grants",
            meta_fields=(("Organization", "organization"), ("Funding", "funding_amount")),
        ),
    ]

    stats = {
        "sources": len(sections),
        "total_saved": sum(section["total_count"] for section in sections),
        "total_shown": sum(section["clean_count"] for section in sections),
        "total_hidden": sum(section["hidden_count"] for section in sections),
    }

    return render(request, "scraper/home.htm", {"sections": sections, "stats": stats})


def run_all(request):
    started = start_scraper_once()
    message = (
        "Scraping Started!"
        if started
        else "Scraping is already running or automatic scraping is disabled."
    )
    return render(request, "scraper/run_all.htm", {"message": message})
