from django.shortcuts import render

from .models import GovService, Grant, IndiaScheme, MyScheme, Scholarship, TenderListing, UmangScheme
from .startup import start_scraper_once


BAD_DISPLAY_PARTS = (
    "request id:",
    "translationdisclaimer",
    "translations of the content",
    "you need to enable javascript",
    "loading...",
    "content sources",
    "view more",
    "toggle faq",
    "screen reader",
    "cpgrams",
    "calendar",
    "current year text",
    "could not find what you were looking for",
    "india portal 2.0 brochure",
    "no data found",
    "okay cancel",
    "skip to main content",
    "pin code",
    "state/district",
    "select category",
    "categoryselect",
    "locationstate",
    "districtpin code",
    "stateandaman",
    "select state",
    "cloudfront",
    "the request could not be satisfied",
    "we can't connect to the server",
    "there might be too much traffic",
    "generated by cloudfront",
)

BAD_SCHOLARSHIP_DISPLAY_PARTS = (
    "top banks for education loan",
    "whatsapp channel",
    "by degree",
    "by subject",
    "by university",
    "by country of interest",
)

FILTER_WORDS = (
    "agriculture",
    "climate change",
    "environmental management",
    "farming",
    "fishing",
    "births, deaths",
    "marriages and child care",
    "citizenship",
    "passports",
    "education and learning",
    "apprenticeships",
    "international grants",
)


def _clean_text(value):
    return " ".join((value or "").split())


def _short_text(value, limit=180):
    value = _clean_text(value)
    if len(value) <= limit:
        return value
    return value[:limit].rstrip() + "..."


def _display_image_url(item):
    image_url = _clean_text(getattr(item, "image_url", "") or "")
    if not image_url:
        return ""

    if isinstance(item, Scholarship):
        provider = _clean_text(getattr(item, "provider", "") or "")
        url = _clean_text(getattr(item, "url", "") or "").lower()

        # Buddy4Study "page" entries often expose banner-like assets instead of usable logos.
        if provider == "Buddy4Study" and "/page/" in url:
            return ""

    return image_url


def _is_displayable(item):
    title = _clean_text(getattr(item, "title", ""))
    lowered = title.lower()
    description = _clean_text(getattr(item, "description", "") or "")
    is_scholarship = isinstance(item, Scholarship)

    if not title or len(title) < 8:
        return False
    if len(title) > 180:
        return False
    if lowered.startswith(("http://", "https://", "www.")):
        return False
    if any(part in lowered for part in BAD_DISPLAY_PARTS):
        return False
    if is_scholarship and any(part == lowered or part in lowered for part in BAD_SCHOLARSHIP_DISPLAY_PARTS):
        return False
    if sum(1 for word in FILTER_WORDS if word in lowered) >= 3:
        return False
    if lowered.endswith(("==", "=")) and len(title) > 25:
        return False
    if title.endswith("More") and not description:
        return False
    if is_scholarship:
        url = _clean_text(getattr(item, "url", "") or "").lower()
        provider = _clean_text(getattr(item, "provider", "") or "")
        has_specific_provider = provider not in {"", "WeMakeScholars", "Buddy4Study"}
        has_detail = any(
            [
                has_specific_provider,
                _clean_text(getattr(item, "deadline", "") or ""),
                _clean_text(getattr(item, "amount", "") or ""),
                _clean_text(getattr(item, "image_url", "") or ""),
            ]
        )
        if (
            url in {
                "https://www.wemakescholars.com/scholarship",
                "https://www.buddy4study.com/scholarships",
            }
            and not has_detail
        ):
            return False
    return True


def _card_from_item(item, meta_fields=(), description_field="description"):
    meta = []
    for label, field in meta_fields:
        value = _clean_text(getattr(item, field, "") or "")
        if value:
            meta.append({"label": label, "value": value})

    return {
        "title": _clean_text(item.title),
        "description": _short_text(getattr(item, description_field, "") or ""),
        "url": item.url,
        "image_url": _display_image_url(item),
        "meta": meta,
    }


def _section(title, queryset, meta_fields=(), description_field="description"):
    total_count = queryset.count()
    clean_items = [
        _card_from_item(item, meta_fields=meta_fields, description_field=description_field)
        for item in queryset.order_by("-id")
        if _is_displayable(item)
    ]

    return {
        "title": title,
        "slug": title.lower().replace(" ", "-"),
        "total_count": total_count,
        "clean_count": len(clean_items),
        "hidden_count": total_count - len(clean_items),
        "items": clean_items,
    }


def home(request):
    sections = [
        _section(
            "UMANG Schemes",
            UmangScheme.objects.all(),
            meta_fields=(("Category", "category"), ("Department", "department")),
        ),
        _section(
            "Government Services",
            GovService.objects.all(),
            meta_fields=(("Type", "service_type"), ("Department", "department")),
        ),
        _section(
            "myScheme",
            MyScheme.objects.all(),
            meta_fields=(("Category", "category"),),
        ),
        _section(
            "India Portal Schemes",
            IndiaScheme.objects.all(),
            meta_fields=(("Category", "category"), ("Ministry", "ministry")),
        ),
        _section(
            "Scholarships",
            Scholarship.objects.all(),
            meta_fields=(("Provider", "provider"), ("Deadline", "deadline"), ("Award", "amount")),
        ),
        _section(
            "Grants",
            Grant.objects.all(),
            meta_fields=(("Organization", "organization"), ("Funding", "funding_amount")),
        ),
        _section(
            "Tender Listings",
            TenderListing.objects.all(),
            meta_fields=(
                ("Source", "source"),
                ("Organization", "organization"),
                ("Location", "location"),
                ("Status", "status"),
                ("Procurement", "procurement_type"),
                ("Value", "tender_value"),
                ("Deadline", "deadline"),
            ),
        ),
    ]

    stats = {
        "sources": len(sections),
        "total_saved": sum(section["total_count"] for section in sections),
        "total_shown": sum(section["clean_count"] for section in sections),
        "total_hidden": sum(section["hidden_count"] for section in sections),
    }

    return render(request, "scraper/home.htm", {"sections": sections, "stats": stats})


def run_all(request):
    started = start_scraper_once()
    message = (
        "Scraping Started!"
        if started
        else "Scraping is already running or automatic scraping is disabled."
    )
    return render(request, "scraper/run_all.htm", {"message": message})
