from django.http import JsonResponse
from django.shortcuts import render
from urllib.parse import unquote

from .mongo import DESCENDING, count_records, find_records, latest_records
from .startup import get_scraper_status, start_scraper_once


BAD_DISPLAY_PARTS = (
    "request id:",
    "translationdisclaimer",
    "translations of the content",
    "you need to enable javascript",
    "loading...",
    "content sources",
    "view more",
    "toggle faq",
    "screen reader",
    "cpgrams",
    "calendar",
    "current year text",
    "could not find what you were looking for",
    "india portal 2.0 brochure",
    "no data found",
    "okay cancel",
    "skip to main content",
    "pin code",
    "state/district",
    "select category",
    "categoryselect",
    "locationstate",
    "districtpin code",
    "stateandaman",
    "select state",
    "cloudfront",
    "the request could not be satisfied",
    "we can't connect to the server",
    "there might be too much traffic",
    "generated by cloudfront",
    "showrecentpopularfilters",
    "homeall categories",
)

BAD_SCHOLARSHIP_DISPLAY_PARTS = (
    "top banks for education loan",
    "whatsapp channel",
    "by degree",
    "by subject",
    "by university",
    "by country of interest",
)

FILTER_WORDS = (
    "agriculture",
    "climate change",
    "environmental management",
    "farming",
    "fishing",
    "births, deaths",
    "marriages and child care",
    "citizenship",
    "passports",
    "education and learning",
    "apprenticeships",
    "international grants",
)

API_FIELDS = {
    "umang": ("id", "title", "description", "category", "department", "url"),
    "gov": ("id", "title", "service_type", "department", "description", "url"),
    "myscheme": (
        "id",
        "title",
        "description",
        "eligibility",
        "benefits",
        "category",
        "ministry",
        "department",
        "level",
        "tags",
        "application_process",
        "documents",
        "references",
        "raw_data",
        "url",
    ),
    "india": ("id", "title", "description", "ministry", "category", "url"),
    "scholarships": ("id", "title", "provider", "deadline", "amount", "image_url", "url"),
    "grants": ("id", "title", "organization", "description", "funding_amount", "url"),
    "tenders": (
        "id",
        "source",
        "external_id",
        "title",
        "organization",
        "location",
        "state",
        "country",
        "status",
        "procurement_type",
        "category",
        "tender_value",
        "published_on",
        "deadline",
        "description",
        "source_url",
        "url",
    ),
}

CARD_RESULT_FIELDS = {
    kind: tuple(field for field in fields if field != "raw_data")
    for kind, fields in API_FIELDS.items()
}

ALL_SCHEME_KINDS = ("umang", "gov", "myscheme", "india")
SCHEME_AND_OPPORTUNITY_KINDS = ALL_SCHEME_KINDS + ("scholarships", "grants", "tenders")

CARD_APIS = {
    "banking-financial-services-and-insurance": {
        "api_key": "banking_financial_services_and_insurance",
        "title": "Banking, Financial Services and Insurance",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("banking,financial services and insurance",),
        "keywords": ("bank", "banking", "finance", "financial", "insurance", "loan", "credit", "pension"),
    },
    "health-wellness": {
        "api_key": "health_wellness",
        "title": "Health & Wellness",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("health & wellness",),
        "keywords": ("health", "healthcare", "wellness", "medical", "medicine", "hospital", "ayush"),
    },
    "housing-shelter": {
        "api_key": "housing_shelter",
        "title": "Housing & Shelter",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("housing & shelter",),
        "keywords": ("housing", "shelter", "house", "home", "awas", "habitat"),
    },
    "public-safety-law-justice": {
        "api_key": "public_safety_law_justice",
        "title": "Public Safety, Law & Justice",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("public safety,law & justice", "public safety, law & justice"),
        "keywords": ("public safety", "law", "justice", "legal", "police", "court", "crime"),
    },
    "science-it-communications": {
        "api_key": "science_it_communications",
        "title": "Science, IT & Communications",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("science, it & communications", "science,it & communications"),
        "keywords": ("science", "technology", "innovation", "digital", "communication", "communications", "it "),
    },
    "skills-employment": {
        "api_key": "skills_employment",
        "title": "Skills & Employment",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("skills & employment",),
        "keywords": ("skill", "employment", "training", "job", "livelihood", "apprentice"),
    },
    "social-welfare-empowerment": {
        "api_key": "social_welfare_empowerment",
        "title": "Social Welfare & Empowerment",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("social welfare & empowerment",),
        "keywords": ("social welfare", "welfare", "empowerment", "social security", "disability", "senior citizen"),
    },
    "sports-culture": {
        "api_key": "sports_culture",
        "title": "Sports & Culture",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("sports & culture",),
        "keywords": ("sports", "sport", "culture", "cultural", "talent", "heritage", "art"),
    },
    "transport-infrastructure": {
        "api_key": "transport_infrastructure",
        "title": "Transport & Infrastructure",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("transport & infrastructure",),
        "keywords": ("transport", "transportation", "infrastructure", "road", "rail", "vehicle"),
    },
    "travel-tourism": {
        "api_key": "travel_tourism",
        "title": "Travel & Tourism",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("travel & tourism",),
        "keywords": ("travel", "tourism", "tourist", "hospitality"),
    },
    "utility-sanitation": {
        "api_key": "utility_sanitation",
        "title": "Utility & Sanitation",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("utility & sanitation",),
        "keywords": ("utility", "sanitation", "water", "drinking water", "sewerage", "electricity"),
    },
    "women-and-child": {
        "api_key": "women_and_child",
        "title": "Women and Child",
        "kinds": ALL_SCHEME_KINDS,
        "category_terms": ("women and child",),
        "keywords": ("women", "woman", "child", "children", "girl", "mother", "family welfare"),
    },
    "agriculture": {
        "api_key": "agriculture",
        "title": "Agriculture",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "category_terms": ("agriculture,rural & environment", "agriculture", "agricultural or forestry"),
        "keywords": ("agriculture", "farmer", "farming", "crop", "kisan", "rural", "fishery", "fisheries"),
    },
    "women-programs": {
        "api_key": "women_programs",
        "title": "Women Programs",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "category_terms": ("women and child",),
        "keywords": ("women", "woman", "girl", "female", "mother", "child", "family welfare"),
    },
    "research-grants": {
        "api_key": "research_grants",
        "title": "Research Grants",
        "kinds": ("grants", "scholarships", "myscheme", "india"),
        "keywords": ("research", "fellowship", "phd", "doctoral", "scientific", "academic", "professor"),
    },
    "tenders-rfps": {
        "api_key": "tenders_rfps",
        "title": "Tenders/RFPs",
        "kinds": ("tenders",),
        "keywords": ("tender", "rfp", "procurement", "bid", "contract"),
    },
    "startup-msme": {
        "api_key": "startup_msme",
        "title": "Startup/MSME",
        "kinds": SCHEME_AND_OPPORTUNITY_KINDS,
        "category_terms": ("business & entrepreneurship",),
        "keywords": ("startup", "start-up", "msme", "business", "entrepreneur", "entrepreneurship", "venture"),
    },
    "scholarships": {
        "api_key": "scholarships",
        "title": "Scholarships",
        "kinds": ("scholarships",),
        "keywords": ("scholarship", "fellowship", "tuition", "student", "education"),
    },
}

DASHBOARD_SOURCES = {
    "umang": {
        "title": "UMANG Schemes",
        "meta_fields": (("Category", "category"), ("Department", "department")),
        "description_field": "description",
    },
    "gov": {
        "title": "Government Services",
        "meta_fields": (("Type", "service_type"), ("Department", "department")),
        "description_field": "description",
    },
    "myscheme": {
        "title": "myScheme",
        "meta_fields": (("Category", "category"), ("Level", "level"), ("Ministry", "ministry")),
        "description_field": "description",
    },
    "india": {
        "title": "India Portal Schemes",
        "meta_fields": (("Category", "category"), ("Ministry", "ministry")),
        "description_field": "description",
    },
    "scholarships": {
        "title": "Scholarships",
        "meta_fields": (("Provider", "provider"), ("Deadline", "deadline"), ("Award", "amount")),
        "description_field": "description",
    },
    "grants": {
        "title": "Grants",
        "meta_fields": (("Organization", "organization"), ("Funding", "funding_amount")),
        "description_field": "description",
    },
}


def _dashboard_projection(kind):
    fields = {"title": 1, "url": 1, "image_url": 1}
    config = DASHBOARD_SOURCES[kind]
    fields[config["description_field"]] = 1
    for _, field in config["meta_fields"]:
        fields[field] = 1

    # These fields are inspected by display filters even when they are not shown.
    for field in (
        "description",
        "service_type",
        "department",
        "eligibility",
        "benefits",
        "provider",
        "deadline",
        "amount",
        "organization",
        "tender_value",
    ):
        fields[field] = 1
    return fields


def _clean_text(value):
    return " ".join((value or "").split())


def _short_text(value, limit=180):
    value = _clean_text(value)
    if len(value) <= limit:
        return value
    return value[:limit].rstrip() + "..."


def _item_kind(item):
    kind = getattr(item, "kind", "")
    if kind:
        return kind

    return {
        "UmangScheme": "umang",
        "GovService": "gov",
        "MyScheme": "myscheme",
        "IndiaScheme": "india",
        "Scholarship": "scholarships",
        "Grant": "grants",
        "TenderListing": "tenders",
    }.get(item.__class__.__name__, "")


def _display_image_url(item):
    image_url = _clean_text(getattr(item, "image_url", "") or "")
    if not image_url:
        return ""

    if _item_kind(item) == "scholarships":
        provider = _clean_text(getattr(item, "provider", "") or "")
        url = _clean_text(getattr(item, "url", "") or "").lower()

        # Buddy4Study "page" entries often expose banner-like assets instead of usable logos.
        if provider == "Buddy4Study" and "/page/" in url:
            return ""

    return image_url


def _source_url(item):
    url = _clean_text(getattr(item, "url", "") or "")
    lowered = url.lower()

    # UMANG records currently only store category SPA URLs, not per-record source pages.
    # Those web.umang.gov.in URLs commonly open as CloudFront 403 pages when clicked directly.
    if _item_kind(item) == "umang" or "web.umang.gov.in" in lowered:
        return ""

    return url


def _search_blob(item):
    values = [
        getattr(item, "title", ""),
        getattr(item, "description", ""),
        getattr(item, "category", ""),
        getattr(item, "department", ""),
        getattr(item, "ministry", ""),
        getattr(item, "service_type", ""),
        getattr(item, "tags", ""),
        getattr(item, "eligibility", ""),
        getattr(item, "benefits", ""),
        getattr(item, "organization", ""),
        getattr(item, "provider", ""),
        getattr(item, "procurement_type", ""),
    ]
    return f" {' '.join(_clean_text(value).lower() for value in values)} "


def _normalized_text(value):
    return (
        _clean_text(value)
        .lower()
        .replace("&", "and")
        .replace(" ,", ",")
        .replace(", ", ",")
    )


def _category_from_source_url(item):
    url = _clean_text(getattr(item, "url", "") or "")
    marker = "/category/"
    if marker not in url:
        return ""
    return unquote(url.rsplit(marker, 1)[-1])


def _category_values(item):
    return [
        getattr(item, "category", ""),
        getattr(item, "department", ""),
        getattr(item, "procurement_type", ""),
        _category_from_source_url(item),
    ]


def _matches_category_terms(item, category_terms):
    if not category_terms:
        return False

    item_values = [
        _normalized_text(value)
        for value in _category_values(item)
        if _normalized_text(value) and _normalized_text(value) != "umang"
    ]

    for term in category_terms:
        normalized_term = _normalized_text(term)
        if not normalized_term:
            continue
        if any(normalized_term == item_value or normalized_term in item_value for item_value in item_values):
            return True
    return False


def _has_meaningful_category(item):
    return any(
        value and value != "umang"
        for value in (_normalized_text(category_value) for category_value in _category_values(item))
    )


def _matches_keywords(item, keywords):
    blob = _search_blob(item)
    return any(keyword.lower() in blob for keyword in keywords)


def _is_startup_or_msme(item):
    organization = _normalized_text(getattr(item, "organization", ""))
    if organization in {"startup grants india", "startup india"}:
        return True
    return _matches_category_terms(item, ("business & entrepreneurship",)) or _matches_keywords(
        item,
        ("startup", "start-up", "msme", "entrepreneur", "entrepreneurship", "venture"),
    )


def _is_research_grant(item):
    kind = _item_kind(item)
    organization = _normalized_text(getattr(item, "organization", ""))
    if kind == "grants" and organization in {"startup grants india", "startup india"}:
        return False
    return _matches_keywords(
        item,
        ("research", "fellowship", "phd", "doctoral", "scientific", "academic", "professor"),
    )


def _matches_card_api(item, config):
    api_key = config["api_key"]

    if api_key == "scholarships":
        return _item_kind(item) == "scholarships"
    if api_key == "tenders_rfps":
        return _item_kind(item) == "tenders"
    if api_key == "startup_msme":
        return _is_startup_or_msme(item)
    if api_key == "research_grants":
        return _is_research_grant(item)

    category_terms = config.get("category_terms", ())
    if _matches_category_terms(item, category_terms):
        return True
    if category_terms and _item_kind(item) in SCHEME_AND_OPPORTUNITY_KINDS and _has_meaningful_category(item):
        return False
    return _matches_keywords(item, config["keywords"])


def _regex_query(field, value):
    return {field: {"$regex": value, "$options": "i"}}


def _card_search_fields(kind):
    fields = ["title", "description", "category", "department", "service_type", "tags", "url"]
    if kind == "grants":
        fields.append("organization")
    if kind == "scholarships":
        fields.extend(["provider", "amount"])
    if kind == "tenders":
        fields.extend(["organization", "procurement_type", "tender_value"])
    return fields


def _card_query_terms(config):
    api_key = config["api_key"]
    if api_key == "scholarships" or api_key == "tenders_rfps":
        return ()
    if api_key == "research_grants":
        return config["keywords"]
    return tuple(config.get("category_terms", ())) + tuple(config["keywords"])


def _card_query(kind, config):
    terms = _card_query_terms(config)
    if not terms:
        return {}

    if config.get("category_terms") and kind in ALL_SCHEME_KINDS:
        fields = ["category", "department", "procurement_type", "url"]
    else:
        fields = _card_search_fields(kind)

    clauses = []
    for field in fields:
        clauses.extend(_regex_query(field, term) for term in terms if term)
    return {"$or": clauses} if clauses else {}


def _card_projection(kind):
    return {field: 1 for field in CARD_RESULT_FIELDS[kind]}


def _is_displayable(item):
    title = _clean_text(getattr(item, "title", ""))
    lowered = title.lower()
    description = _clean_text(getattr(item, "description", "") or "")
    kind = _item_kind(item)
    is_scholarship = kind == "scholarships"

    if not title or len(title) < 8:
        return False
    if len(title) > 180:
        return False
    if lowered.startswith(("http://", "https://", "www.")):
        return False
    if any(part in lowered for part in BAD_DISPLAY_PARTS):
        return False
    if is_scholarship and any(part == lowered or part in lowered for part in BAD_SCHOLARSHIP_DISPLAY_PARTS):
        return False
    if sum(1 for word in FILTER_WORDS if word in lowered) >= 3:
        return False
    if lowered.endswith(("==", "=")) and len(title) > 25:
        return False
    if title.endswith("More") and not description:
        return False
    if kind == "gov":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "service_type", "") or ""),
                _clean_text(getattr(item, "department", "") or ""),
            ]
        )
        if not has_detail:
            return False
    if kind == "myscheme":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "eligibility", "") or ""),
                _clean_text(getattr(item, "benefits", "") or ""),
            ]
        )
        if not has_detail:
            return False
    if is_scholarship:
        url = _clean_text(getattr(item, "url", "") or "").lower()
        provider = _clean_text(getattr(item, "provider", "") or "")
        has_specific_provider = provider not in {"", "WeMakeScholars", "Buddy4Study"}
        has_detail = any(
            [
                has_specific_provider,
                _clean_text(getattr(item, "deadline", "") or ""),
                _clean_text(getattr(item, "amount", "") or ""),
                _clean_text(getattr(item, "image_url", "") or ""),
            ]
        )
        if (
            url in {
                "https://www.wemakescholars.com/scholarship",
                "https://www.buddy4study.com/scholarships",
            }
            and not has_detail
        ):
            return False
    if kind == "tenders":
        has_detail = any(
            [
                description,
                _clean_text(getattr(item, "organization", "") or ""),
                _clean_text(getattr(item, "deadline", "") or ""),
                _clean_text(getattr(item, "tender_value", "") or ""),
            ]
        )
        if not has_detail:
            return False
    return True


def _card_from_item(item, meta_fields=(), description_field="description"):
    meta = []
    for label, field in meta_fields:
        value = _clean_text(getattr(item, field, "") or "")
        if value:
            meta.append({"label": label, "value": value})

    return {
        "title": _clean_text(item.title),
        "description": _short_text(getattr(item, description_field, "") or ""),
        "url": _source_url(item),
        "image_url": _display_image_url(item),
        "meta": meta,
    }


def _card_search_text(card):
    meta_values = " ".join(meta["value"] for meta in card["meta"])
    return _clean_text(f"{card['title']} {card['description']} {meta_values}")


def _dashboard_cards(kind, offset=0, limit=100):
    config = DASHBOARD_SOURCES[kind]
    records = latest_records(
        kind,
        limit=limit,
        skip=offset,
        projection=_dashboard_projection(kind),
    )
    cards = [
        _card_from_item(
            item,
            meta_fields=config["meta_fields"],
            description_field=config["description_field"],
        )
        for item in records
        if _is_displayable(item)
    ]
    for card in cards:
        card["search_text"] = _card_search_text(card)
    return records, cards


def _section(title, kind, meta_fields=(), description_field="description", display_limit=24):
    total_count = count_records(kind)
    preview_items, clean_items = _dashboard_cards(kind, limit=display_limit)
    checked_count = len(preview_items)

    return {
        "title": title,
        "slug": title.lower().replace(" ", "-"),
        "kind": kind,
        "total_count": total_count,
        "checked_count": checked_count,
        "clean_count": len(clean_items),
        "hidden_count": checked_count - len(clean_items),
        "items": clean_items,
    }


def _absolute_request_url(request, url):
    url = _clean_text(url)
    if not url:
        return ""
    return request.build_absolute_uri(url)


def _serialize_item(item, fields):
    return {
        field: getattr(item, field)
        for field in fields
    }


def _filtered_items(kind, predicate=None, limit=None):
    items = []
    for item in latest_records(kind, limit=limit):
        if not _is_displayable(item):
            continue
        if predicate is not None and not predicate(item):
            continue
        items.append(item)
    return items


def _api_response(request, source, kind, fields, api_key=None, predicate=None):
    items = [
        _serialize_item(item, fields)
        for item in _filtered_items(kind, predicate=predicate)
    ]
    return JsonResponse({
        "source": source,
        "api_key": api_key or kind,
        "count": len(items),
        "results": items,
    })


def _card_api_url(request, slug):
    return _absolute_request_url(request, f"/api/cards/{slug}/")


def _card_api_payload(slug):
    config = CARD_APIS.get(slug)
    if not config:
        config = next(
            (
                card_config
                for card_config in CARD_APIS.values()
                if card_config["api_key"] == slug
            ),
            None,
        )
    if not config:
        return None

    results = []
    for kind in config["kinds"]:
        candidates = find_records(
            kind,
            query=_card_query(kind, config),
            sort=[("_id", DESCENDING)],
            projection=_card_projection(kind),
        )
        for item in candidates:
            if not _is_displayable(item):
                continue
            if not _matches_card_api(item, config):
                continue
            row = _serialize_item(item, CARD_RESULT_FIELDS[kind])
            row["source_key"] = kind
            results.append(row)

    return {
        "source": config["title"],
        "api_key": config["api_key"],
        "count": len(results),
        "results": results,
    }


def api_index(request):
    endpoints = {
        "umang_schemes": _absolute_request_url(request, "/api/umang-schemes/"),
        "government_services": _absolute_request_url(request, "/api/government-services/"),
        "myscheme": _absolute_request_url(request, "/api/myscheme/"),
        "india_portal_schemes": _absolute_request_url(request, "/api/india-portal-schemes/"),
        "scholarships": _absolute_request_url(request, "/api/scholarships/"),
        "grants": _absolute_request_url(request, "/api/grants/"),
        "tenders": _absolute_request_url(request, "/api/tenders/"),
        "scraper_status": _absolute_request_url(request, "/api/scraper-status/"),
    }
    card_endpoints = {
        config["api_key"]: _card_api_url(request, slug)
        for slug, config in CARD_APIS.items()
    }
    return JsonResponse({"endpoints": endpoints, "card_endpoints": card_endpoints})


def api_umang_schemes(request):
    return _api_response(
        request,
        "UMANG Schemes",
        "umang",
        API_FIELDS["umang"],
        api_key="umang_schemes",
    )


def api_government_services(request):
    return _api_response(
        request,
        "Government Services",
        "gov",
        API_FIELDS["gov"],
        api_key="government_services",
    )


def api_myscheme(request):
    return _api_response(
        request,
        "myScheme",
        "myscheme",
        API_FIELDS["myscheme"],
        api_key="myscheme",
    )


def api_india_portal_schemes(request):
    return _api_response(
        request,
        "India Portal Schemes",
        "india",
        API_FIELDS["india"],
        api_key="india_portal_schemes",
    )


def api_scholarships(request):
    return _api_response(
        request,
        "Scholarships",
        "scholarships",
        API_FIELDS["scholarships"],
        api_key="scholarships",
    )


def api_grants(request):
    return _api_response(
        request,
        "Grants",
        "grants",
        API_FIELDS["grants"],
        api_key="grants",
    )


def api_tenders(request):
    return _api_response(
        request,
        "Tenders/RFPs",
        "tenders",
        API_FIELDS["tenders"],
        api_key="tenders",
    )


def api_card(request, slug):
    payload = _card_api_payload(slug)
    if payload is None:
        return JsonResponse({"error": "Unknown card API."}, status=404)
    return JsonResponse(payload)


def api_dashboard_records(request, kind):
    if kind not in DASHBOARD_SOURCES:
        return JsonResponse({"error": "Unknown dashboard source."}, status=404)

    try:
        offset = max(0, int(request.GET.get("offset", "0")))
        limit = max(1, min(250, int(request.GET.get("limit", "100"))))
    except ValueError:
        return JsonResponse({"error": "Offset and limit must be numbers."}, status=400)

    total_count = count_records(kind)
    checked_items, clean_items = _dashboard_cards(kind, offset=offset, limit=limit)
    checked_count = len(checked_items)
    next_offset = offset + checked_count

    return JsonResponse({
        "source": DASHBOARD_SOURCES[kind]["title"],
        "kind": kind,
        "total_count": total_count,
        "offset": offset,
        "next_offset": next_offset,
        "checked_count": checked_count,
        "clean_count": len(clean_items),
        "done": next_offset >= total_count or checked_count == 0,
        "items": clean_items,
    })


def api_scraper_status(request):
    return JsonResponse(get_scraper_status())


def home(request):
    sections = [
        _section(config["title"], kind)
        for kind, config in DASHBOARD_SOURCES.items()
    ]

    stats = {
        "sources": len(sections),
        "total_saved": sum(section["total_count"] for section in sections),
        "total_shown": sum(section["clean_count"] for section in sections),
        "total_hidden": sum(section["hidden_count"] for section in sections),
    }

    return render(request, "scraper/home.htm", {"sections": sections, "stats": stats})


def run_all(request):
    started = start_scraper_once()
    message = (
        "Scraping Started!"
        if started
        else "Scraping is already running or automatic scraping is disabled."
    )
    return render(request, "scraper/run_all.htm", {"message": message})
