# Generated by Django 6.0.4 on 2026-04-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(max_length=500)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('procurement_type', models.CharField(blank=True, max_length=120, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('tender_value', models.CharField(blank=True, max_length=120, null=True)),
                ('published_on', models.CharField(blank=True, max_length=120, null=True)),
                ('deadline', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
