# Generated by Django 6.0.4 on 2026-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_tenderlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
