# Generated by Django 6.0.4 on 2026-05-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_govservice_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govservice',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='govservice',
            name='service_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='funding_amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grant',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indiascheme',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='indiascheme',
            name='ministry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myscheme',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myscheme',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myscheme',
            name='level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myscheme',
            name='ministry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='deadline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='procurement_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='published_on',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenderlisting',
            name='tender_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='umangscheme',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='umangscheme',
            name='department',
            field=models.TextField(blank=True, null=True),
        ),
    ]
